name: Daily Scrape Update

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run the scrape script
        run: node scrape.js

      # New steps to verify the JSON files
      - name: Check All.Games.json
        run: |
          if [ ! -f All.Games.json ]; then
            echo "All.Games.json does not exist!";
            exit 1;
          fi

      - name: Check New.Games.json
        run: |
          if [ ! -f New.Games.json ]; then
            echo "New.Games.json does not exist!";
            exit 1;
          fi

      - name: Validate All.Games.json and New.Games.json
        run: |
          if ! jq . All.Games.json; then
            echo "All.Games.json is not valid JSON!";
            exit 1;
          fi
          if ! jq . New.Games.json; then
            echo "New.Games.json is not valid JSON!";
            exit 1;
          fi
